apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-staging
  namespace: techx-trainee-staging
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: registry.hub.docker.com/pttzx/nodeapp:##VERSION##
        ports:
        - containerPort: 3001
      imagePullSecrets:
       - name: regcred
        